### ISSUE TITLE
Not able to login?

### ISSUE THREAD

**Issue by snrgarb** [misread/toontown-launcher-patcher#5]
I create a database etc etc. then when I try and login it says failed? I've manually inserted it into the database and it's not working?

Help?

**Comment by diagnose** [comment]
Your database matches the README exactly, correct?

Also, make sure you've added your [database connection info](https://github.com/misread/toontown-launcher-patcher/blob/master/api/login/index.php#L11-L14). Assuming you're on a shared host, your `$DB_HOST` is localhost, but you'll have to check your web host for login information, database name, etc.

Feel free to reopen this if you're still having trouble.

**Comment by snrgarb** [comment]
Yeah everything matches? I'm still having issues. Everything works. So my database host is 'localhost' cause i'm hosting it off my VPS that i've bought and whenever I manually insert the username into the database it comes up with the error of 'Wrong Username/Password', but when I change the database host to the IP of the vps it comes up with the launcher error of 'There was a problem trying to check Account ID' I'm very confused.

**Comment by diagnose** [comment]
I think I'm starting to understand your problem better.

The error you get with the problem checking the ID is good. That means your database can't be connect to remotely, which is a _massive_ security issue. I'm assuming you entered the password directly into the database, which is also a security issue. It needs to be hashed via the `password_hash('password', PASSWORD_DEFAULT);` method. Since it isn't hashed, it can't verify your raw password with the hashed password.

If you want to do it through your terminal, just run type `php` if I remember correctly, and then echo the password_hash command. It should generate you a hash to store in your database.

**Comment by snrgarb** [comment]
Alright I slightly understand this, let me break it down.
You want me to type "php password_hash('mypassword, PASSWORD_DEFAULT);" into my ubuntu terminal?

Sorry, this is my weak point in my mysql database knowledge

**Comment by diagnose** [comment]
If I remember correctly, you'll just want to type "php" first, and then the password command.

**Comment by snrgarb** [comment]
It says "unexpected token ("

**Comment by snrgarb** [comment]
Message me over skype @ gabriel.william64 Skype would be a lot helpful so I know when you message me.

**Comment by diagnose** [comment]
Resolved
